name: ChestEmpty
main: in.nikitapek.chestempty.ChestEmptyPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin which allows you to empty chests using commands.
dev-url: http://github.com/Indiv0/ChestEmpty/

commands:
  chestempty:
    description: Controls all ChestEmpty functions.
    aliases: [ce, chest_empty, chestEmpty]
    usage: |
      /<command> toggle - Toggle selection mode.
      /<command> undo - Restores last deleted items into the chest.
    permission: chestempty.chestempty
    permission-message: Sorry, you don't have permission to use ChestEmpty
  chestempty toggle:
    description: Toggles selection mode.
  chestempty undo:
    description: Restores the last deleted items into the chest.

permissions:
  chestempty.*:
    description: Gives access to all ChestEmpty commands
    children:
      chestempty.toggle: true
      chestempty.undo: true
