name: ChestEmpty
main: in.nikitapek.chestempty.ChestEmptyPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin which allows you to empty chests using commands.
dev-url: http://github.com/Indiv0/ChestEmpty/

commands:
  chestempty:
    description: Controls all ChestEmpty functions.
    aliases: [ce, chest_empty, chestEmpty]
    usage: |
      /<command> toggle - Toggle selection mode
      /<command> undo - Restores last deleted items into the chest

permissions:
  chestempty.chestempty.toggle:
    children:
      chestempty.chestempty: true
  chestempty.chestempty.undo:
      chestempty.chestempty: true
